### PR TITLE
Support gcs-connector 3.x in GcsUtil

### PR DESCRIPTION
**Pull request by clairemcginty**
Rationale:

I would like to use [gcs-connector](https://github.com/GoogleCloudDataproc/hadoop-connectors/tree/master/gcs) 3.x, which supports the new Parquet VectorIO feature. However, gcs-connector 3.x also drops Java 8 and targets Java 11, which blocks us from upgrading it directly in Beam, since Beam is still targeting 8 (see #31678).

Additionally, as a Beam user, I can't just upgrade gcs-connector on my end, due to breaking changes in how `GoogleCloudStorageImpl` is instantiated: in 2.x it has [public constructors](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.26/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java#L302-L394), but in 3.x it [drops the public constructors and enforces a Builder pattern](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v3.0.4/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java#L2496-L2517). 

Therefore, when running on gcs-connector 3.x, my pipeline throws a NoSuchMethodError from `org.apache.beam.sdk.extensions.gcp.util.GcsUtil` when it tries to invoke the 2.x constructor: https://github.com/apache/beam/blob/v2.61.0/sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java#L727

This PR adds a pipeline option for a GoogleCloudStorage Provider, so that users who want to use gcs-connector 3.x can be unblocked from doing so. It defaults to invoking the gcs-connector 2.x public constructor, but 3.x users can override it to use the Builder.

------------------------

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptions.java [hunk 1]
```diff
@@ -208,4 +222,13 @@ public PathValidator create(PipelineOptions options) {
...
     }
   }
+
+  @FunctionalInterface
+  public interface GoogleCloudStorageProvider {
+    GoogleCloudStorage get(
+        GoogleCloudStorageOptions options,
+        Storage storage,
+        Credentials credentials,
+        HttpRequestInitializer httpRequestInitializer);
```
Comment (clairemcginty) [inline sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptions.java:232]: These 4 params should cover both the [2.x constructor](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v2.2.26/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java#L302-L394) and the [3.x Builder](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/v3.0.4/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java#L2496-L2517)

**Comment by clairemcginty** [comment]
cc @Abacn - wdyt of this workaround for gcs-connector 3.x?

**Comment by Abacn** [comment]
Hi, thanks for the investigation. Is the builder constructor also supported on 2.x ? If so we can just change to use it in all case and no need extra options exposed to user

**Comment by clairemcginty** [comment]
> Hi, thanks for the investigation. Is the builder constructor also supported on 2.x ? If so we can just change to use it in all case and no need extra options exposed to user

Unfortunately it isn't :/ There is no way to construct a `GoogleCloudStorageImpl` that works for both gcs-connector 2.x and 3.x (at least as far as I've been able to find).

**Review by Abacn — APPROVED** [review]
understand, thanks!

**Comment by Abacn** [comment]
java precommit tineout for several rerun. It's passing on HEAD, could you please taking a look if it is related to this change?

**Comment by clairemcginty** [comment]
> looks like it is coded in test to prevent the exposure of unwanted classes. Refactor in a way that does not leak these may fix

thanks for looking into it @Abacn !  hmm, this seems challenging to refactor since the exposure is coming from `interface com.google.cloud.hadoop.gcsio.GoogleCloudStorage` itself... and there's no superclass/subclass that would be appropriate to substitute in here. I guess instead of adding a provider for a `GoogleCloudStorage` instance, we could add a provider for a `BiFunction<StorageResourceId, CreateObjectOptions, WritableByteChannel>` ?

**Comment by clairemcginty** [comment]
> > looks like it is coded in test to prevent the exposure of unwanted classes. Refactor in a way that does not leak these may fix
> 
> hmm, this seems challenging to refactor since the exposure is coming from `interface com.google.cloud.hadoop.gcsio.GoogleCloudStorage` itself... and there's no superclass/subclass that would be appropriate to substitute in here. I guess instead of adding a provider for a `GoogleCloudStorage` instance, we could add a provider for a `BiFunction<StorageResourceId, CreateObjectOptions, WritableByteChannel>` ? Although that would leak more implementation details to the user.

hey @Abacn ! just wanted to ping this thread before the PR goes stale :)

**Comment by Abacn** [comment]
a last resort would be using reflection to handle both constructor or builder. Say, use a try to encapsulate the constictor call, when using 3.x dependency ut will throw an error, catch that Exception and construct the instance using Reflection. Is that possible to do?

**Comment by clairemcginty** [comment]
> a last resort would be using reflection to handle both constructor or builder. Say, use a try to encapsulate the constictor call, when using 3.x dependency ut will throw an error, catch that Exception and construct the instance using Reflection. Is that possible to do?

I think that makes sense... so we'd keep the official Beam dep on 2.x. but try to reflectively construct a 3.x instance first?

**Comment by clairemcginty** [comment]
seems to work! tested it on 2.x and 3.x 👍

File: sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java [hunk 2]
```diff
@@ -739,7 +741,42 @@ public WritableByteChannel create(GcsPath path, CreateOptions options) throws IO
 
   GoogleCloudStorage createGoogleCloudStorage(
       GoogleCloudStorageOptions options, Storage storage, Credentials credentials) {
-    return new GoogleCloudStorageImpl(options, storage, credentials);
+    try {
+      // Attempt to construct gcs-connector 3.x-style GoogleCloudStorage, which is created
+      // exclusively via Builder method; this can be replaced once Java 8 is dropped and
```
Comment (Abacn) [inline sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java:746]: could add a // TODO tag like

// TODO eliminate reflection once Beam drops Java 8 support and upgrade to use gcsio 3.x

Comment (clairemcginty) [reply sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java]: good idea- updated 👍

**Comment by Abacn** [comment]
Sorry for another late request

I've been a little bit worry about relying on the `try {} catch {}` to determine the code path, which happened to bring out performance regression in #33575

since using Reflection is already a hack, I do not see a good solution to this either. But could we try {return new GoogleCloudStorageImpl(...)} first? So in the default dependency versions (gcs 2.x), it won't throw Exception (even though it is handled) after this change

**Comment by clairemcginty** [comment]
that makes sense @Abacn ! Updated so that we try to the 2.x constructor first and attempt the 3.x Builder only if that throws a `NoSuchMethodError`.

**Comment by clairemcginty** [comment]
looks like there was a spotbugs error - looking into it now..

**Comment by Abacn** [comment]
yeah, can be found in "SpotBugs Results": https://github.com/apache/beam/actions/runs/12768890245?pr=33368

```

Code | Warning
-- | --
REC | Exception is caught when Exception is not thrown in org.apache.beam.sdk.extensions.gcp.util.GcsUtil.createGoogleCloudStorage(GoogleCloudStorageOptions, Storage, Credentials)
  | Bug type REC_CATCH_EXCEPTION (click for details)In class org.apache.beam.sdk.extensions.gcp.util.GcsUtilIn method org.apache.beam.sdk.extensions.gcp.util.GcsUtil.createGoogleCloudStorage(GoogleCloudStorageOptions, Storage, Credentials)At GcsUtil.java:[line 780]

Code	Warning
REC	Exception is caught when Exception is not thrown in org.apache.beam.sdk.extensions.gcp.util.GcsUtil.createGoogleCloudStorage(GoogleCloudStorageOptions, Storage, Credentials)
[Bug type REC_CATCH_EXCEPTION (click for details)](https://github.com/apache/beam/pull/33368#REC_CATCH_EXCEPTION)
In class org.apache.beam.sdk.extensions.gcp.util.GcsUtil
In method org.apache.beam.sdk.extensions.gcp.util.GcsUtil.createGoogleCloudStorage(GoogleCloudStorageOptions, Storage, Credentials)
At GcsUtil.java:[line 780]
```

File: sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java [hunk 3]
```diff
@@ -739,7 +741,47 @@ public WritableByteChannel create(GcsPath path, CreateOptions options) throws IO
...
+            builderClass.getMethod("setHttpRequestInitializer", HttpRequestInitializer.class);
+        setHttpRequestInitializerMethod.setAccessible(true);
+        builder = setHttpRequestInitializerMethod.invoke(builder, httpRequestInitializer);
+
+        final Method buildMethod = builderClass.getMethod("build");
+        buildMethod.setAccessible(true);
+        return (GoogleCloudStorage) buildMethod.invoke(builder);
+      } catch (Exception reflectionError) {
+        throw new RuntimeException(
+            "Failed to construct GoogleCloudStorageImpl from gcsio 3.x Builder", e);
```
[the remark this answers is not in the document]
Comment (clairemcginty) [reply sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/util/GcsUtil.java]: Thanks for spotting that! Fixed

**Review by Abacn — APPROVED** [review]
