### ISSUE TITLE
[Bug]: 'BlobProperties' object has no attribute 'properties'

### ISSUE THREAD

**Issue by creste** [apache/beam#24440]
### What happened?

`BlobStorageIO.checksum()` has this line of code:
https://github.com/apache/beam/blob/9915ec466b217dc79ae47d0d318f73ad174da626/sdks/python/apache_beam/io/azure/blobstorageio.py#L378

Which fails with this error:
>AttributeError: 'BlobProperties' object has no attribute 'properties'

Because the [BlobProperties](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobproperties?view=azure-python) class does not have a `properties` attribute.

This fixes the problem:
```python
return self._blob_properties(path).etag
```

### Issue Priority

Priority: 1

### Issue Component

Component: io-py-ideas

**Comment by Abacn** [comment]
Thanks for reporting this. Looks like an obvious mistake introduced in #17380. Will open a PR for fix.

**Comment by Abacn** [comment]
.take-issue
