### PR TITLE
Add hamcrest as an implementation dependency

### LINKED ISSUE #30617: [Bug]: hamcrest required in class path in 2.55.0
### What happened?

Found during 2.55.0RC1 release validation against Dataflow template

This used to work in Beam 2.54.0

```java

// Main.java
PipelineOptions options = PipelineOptionsFactory.fromArgs(argv).withValidation().create();
```

```gradle

// Build.gradle

dependencies {
    implementation(group: 'org.apache.beam', name: 'beam-sdks-java-io-google-cloud-platform', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
    implementation(group: 'org.apache.beam', name: 'beam-sdks-java-core', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
    implementation(group: 'org.apache.beam', name: 'beam-runners-direct-java', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
}
```

However, in Beam 2.55.0RC1, there is exception thrown (see https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/8251849699?pr=1361):

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/Matcher
        ...
        at org.apache.beam.sdk.options.PipelineOptionsFactory.<clinit>(PipelineOptionsFactory.java:543)
        at com.github.abacn.MinimumStreaming.main(MinimumStreaming.java:19)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 34 more
```

The interface failed to create is TestBigQueryOptions which extends TestPipelineOptions. In TestPipelineOptions, some methods return org.hamcrest.Matcher: https://github.com/apache/beam/blob/986f67fd92b27dee0c95c5965de98ba6f84a0143/sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipelineOptions.java#L45

It seems beam actually always requires org.hamcrest present in runtime class path. Indeed, another minimum test fails on both 2.54.0 and 2.55.0:

```java

PipelineOptions options = PipelineOptionsFactory.fromArgs(argv).withValidation().as(TestPipelineOptions.class);
```

```gradle

dependencies {
    implementation(group: 'org.apache.beam', name: 'beam-sdks-java-core', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
    implementation(group: 'org.apache.beam', name: 'beam-runners-direct-java', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
}
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fix #30617

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/io/google-cloud-platform/build.gradle [hunk 1]
```diff
@@ -116,8 +116,8 @@ dependencies {
   permitUnusedDeclared library.java.grpc_google_cloud_pubsublite_v1 // BEAM-11761
   implementation library.java.guava
   implementation library.java.http_client
-  provided library.java.hamcrest
-  permitUnusedDeclared library.java.hamcrest // BEAM-11761
+  implementation library.java.hamcrest
+  permitUnusedDeclared library.java.hamcrest // Needed for PipelineOptionRegistrar auto-service that registered TestPipelineOptions interfaces
```
Comment (kennknowles) [inline sdks/java/io/google-cloud-platform/build.gradle:120]: This is interesting. Somehow I though it was a direct dependency within the code. Is it actually something upstream that has hamcrest as a provided dependency still?

Comment (Abacn) [reply sdks/java/io/google-cloud-platform/build.gradle:120]: Yes, it's java-core also have hamcrest as a provided dependency: https://github.com/apache/beam/blob/3aa78d21f70eb2e4236ac86281cf037896e6faed/sdks/java/core/build.gradle#L108

and the reflection access of TestPipeline sub-interfaces need hamcrest because it is a return type of a interface method: https://github.com/apache/beam/blob/3aa78d21f70eb2e4236ac86281cf037896e6faed/sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipelineOptions.java#L47
