### PR TITLE
fix circular PipelineGraph import

### PR DESCRIPTION
**Pull request by derrickaw**
1. Current code has circular import - causing failures with https://github.com/apache/beam/actions/runs/20287544814
2. Move import to _get_pipeline_graph to allow module to fully load before importing.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by derrickaw** [comment]
Run Python_Transforms PreCommit 3.13

**Comment by shunping** [comment]
Let's monitor the test run tonight: 
https://github.com/apache/beam/actions/workflows/beam_Playground_CI_Nightly.yml

**Comment by shunping** [comment]
> Let's monitor the test run tonight: https://github.com/apache/beam/actions/workflows/beam_Playground_CI_Nightly.yml

Looks like this workflow is always running against a released version.

https://github.com/apache/beam/actions/runs/20321904216/workflow#L86

So it will be there until we have a new release...

cc'ed @damccorm

**Comment by shunping** [comment]
I took one example from the error and tried on playground, but could not see the error in the UI. Maybe the website and the test here are going through different code paths?
```
[2025-12-18 00:49:52,176] ERROR [root._verify_examples:220] Example: /runner/_work/beam/beam/./sdks/python/apache_beam/examples/snippets/transforms/aggregation/groupby_two_exprs.py has execution error: error: exit status 1
output: /usr/local/lib/python3.10/site-packages/google/api_core/_python_version_support.py:266: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "/opt/playground/backend/executable_files/e8c3718c-16af-446a-96c7-56d5c77975be/e8c3718c-16af-446a-96c7-56d5c77975be.py", line 58, in <module>
    groupby_two_exprs()
  File "/opt/playground/backend/executable_files/e8c3718c-16af-446a-96c7-56d5c77975be/e8c3718c-16af-446a-96c7-56d5c77975be.py", line 49, in groupby_two_exprs
    from apache_beam.runners.interactive.display import pipeline_graph
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/interactive/display/pipeline_graph.py", line 37, in <module>
    from apache_beam.runners.interactive import interactive_environment as ie
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/interactive/interactive_environment.py", line 41, in <module>
    from apache_beam.runners.interactive.recording_manager import RecordingManager
  File "/usr/local/lib/python3.10/site-packages/apache_beam/runners/interactive/recording_manager.py", line 44, in <module>
    from apache_beam.runners.interactive.display.pipeline_graph import PipelineGraph
ImportError: cannot import name 'PipelineGraph' from partially initialized module 'apache_beam.runners.interactive.display.pipeline_graph' (most likely due to a circular import) (/usr/local/lib/python3.10/site-packages/apache_beam/runners/interactive/display/pipeline_graph.py)
```

https://play.beam.apache.org/?path=SDK_PYTHON_GroupByTwoExprs&sdk=python

**Comment by shunping** [comment]
Looks like we are using an old python backend image for the playground, so the error is currently not shown on the playground website. 

image


image

**Comment by shunping** [comment]
@derrickaw: looks like there is another circular import problem of `RecordingManager`, introduced in #36853.

```
Traceback (most recent call last):
  File "./sdks/python/playpen/import_loop", line 3, in <module>
    from apache_beam.runners.interactive.recording_manager import RecordingManager
  File "./sdks/python/apache_beam/runners/interactive/recording_manager.py", line 38, in <module>
    from apache_beam.runners.interactive import background_caching_job as bcj
  File "./sdks/python/apache_beam/runners/interactive/background_caching_job.py", line 46, in <module>
    from apache_beam.runners.interactive import interactive_environment as ie
  File "./sdks/python/apache_beam/runners/interactive/interactive_environment.py", line 41, in <module>
    from apache_beam.runners.interactive.recording_manager import RecordingManager
ImportError: cannot import name 'RecordingManager' from partially initialized module 'apache_beam.runners.interactive.recording_manager' (most likely due to a circular import) (./sdks/python/apache_beam/runners/interactive/recording_manager.py)
```
