### PR TITLE
[BEAM-12361] Ensure that Reshuffle.AssignToShard numBuckets is respected

### PR DESCRIPTION
**Pull request by egalpin**
Reshuffle.AssignToShard[1] produces (N*2)-1 buckets, where N is the value of the user-defined numBuckets parameter. This is because the value of the  variable having the remainder operator applied, hashOfShard, can be negative and Java's `%` operator has the semantics of `remainder` rather than `modulus`. 

Is it intentional to produce  (N*2)-1 buckets?

We should consider the implications of changing this Reshuffle behavior for use cases already employing AssignToShard. Until recently (28 days ago[2]) the class was private, plus Reshuffle is marked as deprecated, so I imagine the impact would be low?

[1] 
https://github.com/apache/beam/blob/abbe14f721327d51cce02876324e7feba98581e2/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/Reshuffle.java#L160
[2] 
https://github.com/apache/beam/commit/abbe14f721327d51cce02876324e7feba98581e2

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Examples testing status on various runners
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Examples_Dataflow_Java11_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Dataflow_V2/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    <tr>
      <td>XLang</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

Post-Commit SDK/Transform Integration Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Go</th>
      <th>Java</th>
      <th>Python</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
  </tbody>
</table>

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>---</th>
      <th>Java</th>
      <th>Python</th>
      <th>Go</th>
      <th>Website</th>
      <th>Whitespace</th>
      <th>Typescript</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Non-portable</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocker_Cron/lastCompletedBuild/">
          Build Status
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_PythonDocs_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Go_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Whitespace_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Typescript_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
    </tr>
    <tr>
      <td>Portable</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_Portable_Python_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PreCommit_GoPortable_Cron/lastCompletedBuild/">
          Build Status
        </a>
      </td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
  </tbody>
</table>

See [.test-infra/jenkins/README](https://github.com/apache/beam/blob/master/.test-infra/jenkins/README.md) for trigger phrase, status and link of all Jenkins jobs.

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by egalpin** [comment]
R: @jkff

**Comment by egalpin** [comment]
R: @amaliujia

**Comment by egalpin** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java [hunk 1]
```diff
@@ -274,4 +277,26 @@ public void testReshuffleWithTimestampsStreaming() {
...
+  @Test
+  @Category({ValidatesRunner.class, UsesTestStream.class})
+  public void testAssignShardFn() {
+
+    PCollection<KV<String, Integer>> input =
+        pipeline
+            .apply(
+                Create.of(ARBITRARY_KVS)
+                    .withCoder(KvCoder.of(StringUtf8Coder.of(), VarIntCoder.of())))
+            .apply(Window.into(new GlobalWindows()));
```
Comment (TheNeuralBit) [inline sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java:290]: The hashing in Reshuffle (and the values in ARBITRARY_KVS) is deterministic right?

We don't need to worry about this flaking and ssometimes not producing a value in every bucket?

**Review by TheNeuralBit — APPROVED** [review]
LGTM, @dpcollins-google could you take a look?

**Comment by TheNeuralBit** [comment]
Run Java_Examples_Dataflow PreCommit

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java (hunk 1 above)
Comment (dpcollins-google) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java:290]: LGTM. This appears to be deterministic as far as I can tell.

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java [hunk 2]
```diff
@@ -274,4 +277,26 @@ public void testReshuffleWithTimestampsStreaming() {
 
     pipeline.run();
   }
+
+  @Test
+  @Category({ValidatesRunner.class, UsesTestStream.class})
```
Comment (iemejia) [inline sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java:282]: Is `TestStream` used in this test? otherwise we should remove the `UsesTestStream` annotation or the test won't be run for some runners.

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java (hunk 1 above)
Comment (iemejia) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java:290]: Is forcing windowing into GlobalWindows necessary here given that it is already a Bounded PCollection?

**Review by iemejia — COMMENTED** [review]
This is a regression introduced in #14404 and now part of 2.30.0 so it should also be cherry-picked

CC: @amaliujia @ihji

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java (hunk 1 above)
Comment (egalpin) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java:290]: @iemejia I don't believe it's necessary, no. It was intended to be explicit but I'm happy to make the test adhere to whatever standard is preferred. I'll remove the global windowing transform since that's implicit with a bounded PCollection

**Comment by egalpin** [comment]
the Dataflow precommit is failing with this error:

```
Reshuffle.java:163: error: [unboxing.of.nullable] unboxing a possibly-null reference numBuckets
.mod(UnsignedInteger.valueOf(numBuckets))
                             ^
```

Yet this code is within a conditional block that only executes if `numBuckets` is not null. I assume this might have something to do with `@Nullable` annotation processing? I'm missing something haha

**Comment by TheNeuralBit** [comment]
> This is a regression introduced in #14404 and now part of 2.30.0 so it should also be cherry-picked

I think #14404 just moved this code around. The function was added in #11919. I think it had this bug from the start so not technically a regression, but I agree it's a good candidate to cherry-pick into 2.30.0 regardless.

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java (hunk 1 above)
Comment (iemejia) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java:290]: @egalpin Well we can let it, it is just that it looks 'repeated' for a bounded collection.

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java (hunk 2 above)
Comment (iemejia) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ReshuffleTest.java]: No, ValidatesRunner makes sense (thanks for fixing the other one), basically it says that all runner implementations should pass this test.

**Comment by egalpin** [comment]
@kennknowles I believe it could be tested via `Reshuffle.withNumBuckets` and then verifying the number of groups in the output PCollection was as expected.  That said, now that `AssignShardFn` is `public`, is it preferable to have tests directly interacting with the class? I'm not sure what the practice is across the code base, happy to adjust to fit!

I do think in either case we'll see this odd `unboxing` error during compilation though. I still haven't gotten to the bottom of that.

**Comment by egalpin** [comment]
Run Java PreCommit

**Comment by egalpin** [comment]
Run Java PreCommit

**Comment by egalpin** [comment]
`:runners:flink:1.12:test` flaking I believe. I don't _think_ it's related to this change but not certain

**Comment by egalpin** [comment]
Run Java PreCommit

**Comment by ihji** [comment]
What's the next step on this PR? Is this okay to be merged?

**Comment by TheNeuralBit** [comment]
Ah yes I think this is ready. I thought we were still blocked on the checker framework issue but it looks like @egalpin resolved that.

Filed BEAM-12361 to track it
