### PR TITLE
Remove sdks/java/fn-execution

### PR DESCRIPTION
**Pull request by kennknowles**
Another part of fixing #30169 (merging runners-core-construction-java into sdks-java-core)

Follow up to #30170 which moved out the code but did not deal with all the dependency repurcusions.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by kennknowles** [comment]
R: @chamikaramj 

Need one more little fix - this successfully isolated the change that caused all the mocking in `DataflowWorkUnitClientTest` to fail. My take on that test is that it has so much mocking it basically tests nothing, so I had just deleted it in my other PR. But with this level of isolation maybe I'll see if I can figure out what is going on. I don't think it has anything to do with functionality, and is just mocking always being a bad idea.

**Comment by kennknowles** [comment]
(noting that the two commits should be kept separate when merging)

File: sdks/java/harness/build.gradle [hunk 1]
```diff
@@ -91,7 +91,7 @@ dependencies {
   testImplementation library.java.junit
   testImplementation library.java.mockito_core
   shadowTestRuntimeClasspath project(path: ":sdks:java:core", configuration: "shadowTest")
-  testImplementation project(path: ":sdks:java:fn-execution", configuration: "testRuntimeMigration")
+  testImplementation project(path: ":sdks:java:core", configuration: "testRuntimeMigration")
```
Comment (Abacn) [inline sdks/java/harness/build.gradle:94]:
```
shadowTestRuntimeClasspath project(path: ":sdks:java:core", configuration: "shadowTest")
testImplementation project(path: ":sdks:java:core", configuration: "testRuntimeMigration")
```
could remove the first one?

Comment (kennknowles) [reply sdks/java/harness/build.gradle:94]: I'm not totally sure - I can try it

Comment (kennknowles) [reply sdks/java/harness/build.gradle:94]: It looks like `testRuntimeMigration` is an intermediate configuration that should have been finished and deleted, perhaps. So it might be weird. Do you know about it?

Comment (Abacn) [reply sdks/java/harness/build.gradle:94]: Yeah `testRuntimeMigration` was introduced in #16307 (upgrade gradle 6->7) to replace the removed `testRuntime`. It should be either `testRuntimeOnly` or `testImplementation`. However, the followup never finished

Comment (kennknowles) [reply sdks/java/harness/build.gradle]: Removing either one causes errors.

Remove `shadowTestRuntimeClasspath project(path: ":sdks:java:core", configuration: "shadowTest")` and the errors are (from a few different tests)

```
java.lang.NoClassDefFoundError: Lorg/apache/beam/sdk/testing/ResetDateTimeProvider;
```

```
java.lang.NoClassDefFoundError: org/apache/beam/sdk/fn/stream/PrefetchableIteratorsTest$ReadyAfterPrefetch
```

```
java.lang.NoClassDefFoundError: Lorg/apache/beam/sdk/testing/ExpectedLogs;
```

I think this is caused by us putting actual logic code in the `src/main/test` directory so it is in the `-tests` jar. That is essentially always wrong to do. That jar should never be used for shared code between modules/dependencies. There have been some tickets filed about it. (the only OK use of tests jar for sharing is if you want to run someone's tests, like how we do validates runner, otherwise it is not OK).

And if we remove `testImplementation project(path: ":sdks:java:core", configuration: "testRuntimeMigration")` it doesn't compile, since `shadowTestRuntimeClasspath` doesn't put it on the compilation classpath.

Using just `shadowTest` seems to work. Pushing that delta and hopefully everything else is still happy.

**Comment by kennknowles** [comment]
I believe the red signal is corruption on the self-hosted runner. I cannot reach any UI that indicates what the failure is.

**Comment by Abacn** [comment]
Yeah, never mind the status of "Test Results". It's a strange issue of GItHub Action reported before: #29091

**Comment by kennknowles** [comment]
It is green other than that. Any other comments?

**Review by Abacn — APPROVED** [review]
Thanks!
