### PR TITLE
Test and fix FlatMap(<builtin>) issue

### LINKED ISSUE #22091: [Bug]: beam.FlatMap(<built-in function>) raises an error at pipeline construction time
### What happened?

This was a regression introduced by 0de98210f4531fbfd88265bc02052b27bd299602, which is in the 2.40.0 release.

When expanding a `FlatMap(<built-in function>)` users will encounter an error:
```
AttributeError: 'builtin_function_or_method' object has no attribute '__func__'
```

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Fixes #22091

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by pabloem** [comment]
lgtm!

**Comment by tvalentyn** [comment]
thanks for adding missing tests.
