### PR TITLE
Fix io-gcp requiring hamcrest dependency

### LINKED ISSUE #30617: [Bug]: hamcrest required in class path in 2.55.0
### What happened?

Found during 2.55.0RC1 release validation against Dataflow template

This used to work in Beam 2.54.0

```java

// Main.java
PipelineOptions options = PipelineOptionsFactory.fromArgs(argv).withValidation().create();
```

```gradle

// Build.gradle

dependencies {
    implementation(group: 'org.apache.beam', name: 'beam-sdks-java-io-google-cloud-platform', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
    implementation(group: 'org.apache.beam', name: 'beam-sdks-java-core', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
    implementation(group: 'org.apache.beam', name: 'beam-runners-direct-java', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
}
```

However, in Beam 2.55.0RC1, there is exception thrown (see https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/8251849699?pr=1361):

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/Matcher
        ...
        at org.apache.beam.sdk.options.PipelineOptionsFactory.<clinit>(PipelineOptionsFactory.java:543)
        at com.github.abacn.MinimumStreaming.main(MinimumStreaming.java:19)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 34 more
```

The interface failed to create is TestBigQueryOptions which extends TestPipelineOptions. In TestPipelineOptions, some methods return org.hamcrest.Matcher: https://github.com/apache/beam/blob/986f67fd92b27dee0c95c5965de98ba6f84a0143/sdks/java/core/src/main/java/org/apache/beam/sdk/testing/TestPipelineOptions.java#L45

It seems beam actually always requires org.hamcrest present in runtime class path. Indeed, another minimum test fails on both 2.54.0 and 2.55.0:

```java

PipelineOptions options = PipelineOptionsFactory.fromArgs(argv).withValidation().as(TestPipelineOptions.class);
```

```gradle

dependencies {
    implementation(group: 'org.apache.beam', name: 'beam-sdks-java-core', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
    implementation(group: 'org.apache.beam', name: 'beam-runners-direct-java', version: "$beam_version") {
        exclude group: "org.hamcrest", module: "hamcrest"
    }
}
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fix #30617

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
The failed PostCommit tests are either due to #30560 or quota error (failed to bring 1 worker)

R: @ahmedabu98 @kennknowles

**Comment by ahmedabu98** [comment]
Can we trigger BQ early rollout tests here? https://github.com/apache/beam/blob/4ad189db26566caa420008f81d289cedd1dbd786/.github/workflows/beam_PostCommit_Java_BigQueryEarlyRollout.yml#L24

**Comment by ahmedabu98** [comment]
Also would it make sense to combine TestBigQueryOptions and BigtableChangeStreamTestOptions in a new `test/.../gcp/common/TestGcpIoPipelineOptionsRegistrar`? instead of having them in separate registrars

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+import org.apache.beam.sdk.options.PipelineOptionsRegistrar;
+import org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableList;
+
+@AutoService(PipelineOptionsRegistrar.class)
+@Internal
+public class TestGcpIoPipelineOptionsRegistrar implements PipelineOptionsRegistrar {
+  @Override
+  public Iterable<Class<? extends PipelineOptions>> getPipelineOptions() {
+    return ImmutableList.<Class<? extends PipelineOptions>>builder()
+        .add(TestBigQueryOptions.class)
```
Comment (kennknowles) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java:34]: These are options for `TestBigQuery` which is intended for users. Anything intended for users should be under `src/main`

**Review by kennknowles — CHANGES_REQUESTED** [review]

**Comment by kennknowles** [comment]
I know it could seem like anything "for testing" goes under `src/test` and should not be in the classpath, but that is not quite true. The only things that go in `src/test` or `test` dependency scope are things that are _part of the test suite_. Nothing should ever depend on the `test` scope artifact, so we shouldn't put anything in it that we want to distribute.

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java (hunk 1 above)
Comment (Abacn) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java:34]: TestBigQueryOptions is still in main. The problem here is there is an AutoService to register TestBigQueryOptions, then whenever a PipelineOptionFactory.fromArgs is called, the PipelineOptionFactory tries to do some reflection access to TestBigQueryOptions which causes `NoClassDefFoundError: org/hamcrest/Matcher`. This is because TestPipelineOptions has a method return a Matcher.

This makes org.hamcrest effectively a required dependency (instead of optional one) for Beam io-gcp.

If do not register TestBigQueryOptions, users can still use it. They just need to register the option before they call PipelineOptionFactory.withValidation().

Comment (Abacn) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java:34]: An alternate fix will just be make it a implementation dependency here:

Comment (kennknowles) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java:34]: Yes, making it an implementation dependency seems correct. It is, after all, an implementation dependency :-)

Comment (kennknowles) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java:34]: hamcrest is a tiny tiny library that is super stable and has no transitive deps and not going to have security concerns - there is no reason to avoid it

Comment (Abacn) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/TestGcpIoPipelineOptionsRegistrar.java:34]: thanks, opened #30635 and close this PR
