### ISSUE TITLE
[Bug]: BC-FIPS compliant app breaks on Beam 2.39.0 when upgrading from 2.34.0

### ISSUE THREAD

**Issue by Firebeam** [apache/beam#22566]
### What happened?

We're currently using a GCP Dataflow app which works fine under 2.34.0, but needs to remain FIPS compliant, this includes having bc-fips-1.0.2.1.jar in our classpath. When we tried to upgrade to 2.39.0, apparently this new version included the jar bcpkix-jdk15on:1.67, which collides with the FIPS implementation, according to this StackOverflow answer: [https://stackoverflow.com/a/71075642](https://stackoverflow.com/a/71075642)

The actual error is as follows:

`org.apache.beam.sdk.util.UserCodeException: java.lang.NoSuchMethodError: 'boolean org.bouncycastle.crypto.CryptoServicesRegistrar.isInApprovedOnlyMode()' at
org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:39)`

Is there a way we can upgrade safely?

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by Firebeam** [comment]
My mistake, the conflicting jar is bcprov-jdk15on, according to this answer. [https://stackoverflow.com/a/65134446](https://stackoverflow.com/a/65134446) I do see the bcpkix-jdk15on dependency on beam-sdks-java-io-google-cloud-platform:2.39.0, under the nested dependency google-cloud-firestore:3.1.0. I'll try removing the bcprov-jdk15on dependency via exclusion, I'd put upgrading aside for now.

**Comment by Firebeam** [comment]
Ok, good news. The workaround, well, works. But there should be a disclaimer for known issue, IMO. Leaving that for consideration!
