### PR TITLE
[BEAM-4038] Support Kafka Headers in KafkaIO

### PR DESCRIPTION
**Pull request by gkumar7**
Adds read support for Kafka headers. These changes have been tested with prior versions of Kafka 0.9.x as well as the latest version (1.0.x). 

Added KafkaHeader, KafkaHeaders, KafkaRecordHeader, KafkaRecordHeaders for backwards compatibility.

### CODE REVIEW

**Comment by gkumar7** [comment]
@rangadi, let me know what you think. Thanks!

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.apache.beam.sdk.io.kafka;
+
+/**
+ * This is a copy of Kafka's {@link org.apache.kafka.common.header.Header}. Included here in order
+ * to support older Kafka versions (0.9.x).
+ */
+public interface KafkaHeader {
```
Comment (rangadi) [inline sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: I think strictly we don't need to our own versions `Header`, `Headers` etc. How about this: 
 - Add 'Headers' field to KafkaRecord. We ensure the field is accessed only if the `consumerSpEL.hasHeaders` is true.
 - add `Headers getHeaders()` method to KafkaRecord, which throws an exception if `hasHeaders` is false.

I think we could have done something like this with `TimestampType` too. WDYT.
It is a bit hacky, but I guess it is better than replicating more of ConsumerRecord functionality.

File: sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java [hunk 2]
```diff
@@ -75,28 +82,22 @@ public void testCustomTimestampPolicyWithLimitedDelay() {
...
-                                        -100_000L,  // <<< Max timestamp
-                                        -110_000L);
+    List<Long> input =
+        ImmutableList.of(
+            -200_000L, -150_000L, -120_000L, -140_000L, -100_000L, // <<< Max timestamp
+            -110_000L);
     assertThat(getTimestampsForRecords(policy, now, input), is(input));
 
     // Watermark should be max_timestamp - maxDelay
-    assertThat(policy.getWatermark(ctx), is(now
```
Comment (rangadi) [inline sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java]: Please remove all of these spurious changes.

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java (hunk 1 above)
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: > Add 'Headers' field to KafkaRecord

Is 'Headers' referring to ```org.apache.kafka.common.header.Headers```? If so, how would this approach work for Kafka 0.9.x (note that this interface is only available in Kafka 0.11.x) ? Wouldn't this lead to a compile-time error?

The main reason we use our own versions of ```Header```, etc is to avoid such compile-time errors.

File: sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java (hunk 2 above)
Comment (gkumar7) [reply sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java]: Sure thing, must be some ide setting I missed.

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java (hunk 1 above)
Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: We want to avoid runtime errors, not compile time. As long as user with older version of Kafka at runtime does not use getHeaders() interface, it will be fine. I tried it in a test program and it worked ok.

Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: We can require recent kafka version to compile and run tests. But at runtime we want KafkaIO to work with older versions of kafka-clients at runtime. That's why we have the runtime reflection checks.

Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: Hmm, when adding ```Headers``` to ```KafkaRecord```, I was not able to instantiate ```KafkaRecord``` in my test program. Compilation failed with:

```
Error:(8, 5) java: cannot access org.apache.kafka.common.header.Headers
  class file for org.apache.kafka.common.header.Headers not found
```
Tried with both JDK 1.7 and 1.8. This is using kafka-clients 0.9.0.0.

Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: As noted in previous two comments, we don't need to support compiling with 0.9. Even master would not not compile with 0.9. We can require 0.11.x (whichever version first included headers) for compilation and to run tests.
If you get the code working with the default version of kafka-clients Beam (I think 1.0.x), that is good enough. During the review we can check if it would work with older version of kafka-clients at runtime.

Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: Yes, I understand. I have removed the additional classes. What I mean to say is if the test program (which depends on beam-kafka) calls KafkaRecord.getHeaders(), this raises a compile error. Is this what we want? 

It seems a bit counter-intuitive to expose a method such as getHeaders() and not be able to compile the program when using it.

Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaHeader.java]: I see. That is correct, compilation error is fine. All the kafka-client versions before 0.10.1 are already deprecated [1]. If a test wants to test kafka headers, it probably makes sense to depend on a kafka-client version that has headers. 

[1]https://github.com/apache/beam/blob/master/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java#L624

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java [hunk 3]
```diff
@@ -33,6 +34,7 @@
   private final String topic;
   private final int partition;
   private final long offset;
+  private final Headers headers;
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: Could you explain how this would work? Marking this as ```@Nullable``` would not help circumvent the issue that ```Headers``` class would still need to be on the classpath. To verify, I made the requested changes and I receive the following runtime error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/common/header/Headers
	at org.apache.beam.sdk.io.kafka.KafkaUnboundedSource.getOutputCoder(KafkaUnboundedSource.java:142)
```

When using kafka-clients 0.10.1.0.

[the remark this answers is not in the document]
Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: can you push your changes? `KafkaRecordCoder` constructor does not access Headers at all. It is accessed only in encode and decode (where we should handle null values for headers).

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java [hunk 4]
```diff
@@ -131,6 +149,7 @@ public long offsetForTime(Consumer<?, ?> consumer, TopicPartition topicPartition
         .offsetsForTimes(ImmutableMap.of(topicPartition, time.getMillis()))
         .values());
 
+
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java]: Done

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java [hunk 5]
```diff
@@ -139,4 +158,14 @@ public long offsetForTime(Consumer<?, ?> consumer, TopicPartition topicPartition
       return offsetAndTimestamp.offset();
     }
   }
+
+  public Headers getHeaders(ConsumerRecord<byte[], byte[]> rawRecord) {
+    Headers recordHeaders = new RecordHeaders();
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java]: Updated, instead of throwing RuntimeException, for now simply returning null.

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java [hunk 6]
```diff
@@ -90,7 +98,7 @@ public KafkaTimestampType getTimestampType() {
 
   @Override
   public int hashCode() {
-    return Arrays.deepHashCode(new Object[]{topic, partition, offset, timestamp, kv});
+    return Arrays.deepHashCode(new Object[] {topic, partition, offset, timestamp, headers, kv});
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: Verified, null works as expected.

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java [hunk 7]
```diff
@@ -55,6 +64,7 @@ public void encode(KafkaRecord<K, V> value, OutputStream outStream) throws IOExc
     longCoder.encode(value.getOffset(), outStream);
     longCoder.encode(value.getTimestamp(), outStream);
     intCoder.encode(value.getTimestampType().ordinal(), outStream);
+    headerCoder.encode(getIterable(value.getHeaders()), outStream);
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java]: Done

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java [hunk 8]
```diff
@@ -66,9 +76,24 @@ public void encode(KafkaRecord<K, V> value, OutputStream outStream) throws IOExc
         longCoder.decode(inStream),
         longCoder.decode(inStream),
         KafkaTimestampType.forOrdinal(intCoder.decode(inStream)),
+        getHeaders(headerCoder.decode(inStream)),
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java]: Done

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java [hunk 9]
```diff
@@ -66,9 +76,24 @@ public void encode(KafkaRecord<K, V> value, OutputStream outStream) throws IOExc
...
         kvCoder.decode(inStream));
   }
 
+  private Headers getHeaders(Iterable<KV<String, byte[]>> records) {
+    Headers headers = new RecordHeaders();
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java]: Instantiating via ```ConsumerRecord``` is a bit hacky. It should be fine if we use ```RecordHeaders``` directly. If it was not meant to be used, it should be encapsulated more thoroughly (package-private).

File: sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java [hunk 10]
```diff
@@ -46,13 +47,14 @@
       .map(ts -> {
         Instant result = policy.getTimestampForRecord(
           null, new KafkaRecord<>("topic", 0, 0, now.getMillis() + ts,
-                                  KafkaTimestampType.CREATE_TIME, "key", "value"));
+                                      KafkaTimestampType.CREATE_TIME,
+                                      new RecordHeaders(),
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java]: Kept headers null for this test, added tests to KafkaRecordCoderTest for null and non-null cases.

File: sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java [hunk 11]
```diff
@@ -79,7 +81,7 @@ public void testCustomTimestampPolicyWithLimitedDelay() {
                                         -150_000L,
                                         -120_000L,
                                         -140_000L,
-                                        -100_000L,  // <<< Max timestamp
+                                        -100_000L, // <<< Max timestamp
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java]: Done

File: sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java [hunk 12]
```diff
@@ -94,7 +96,7 @@ public void testCustomTimestampPolicyWithLimitedDelay() {
                              -150_000L,
                              -120_000L,
                              -140_000L,
-                              100_000L,  // <<< timestamp is in future
+                             100_000L, // <<< timestamp is in future
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/CustomTimestampPolicyWithLimitedDelayTest.java]: Done

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: Sure will do. See updated comment above.

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java [hunk 13]
```diff
@@ -76,6 +80,10 @@ public long getOffset() {
     return offset;
   }
 
+  public Headers getHeaders() {
```
[the remark this answers is not in the document]
Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: I think this should throw an exception if 'hasHeaders' is false. We don't need the user to worry about null values. `ConsumerRecord.headers` is not expected to be null either. We can do this once we know the current solution works as expected with older kafka-clients versions.

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java [hunk 14]
```diff
@@ -66,9 +77,32 @@ public void encode(KafkaRecord<K, V> value, OutputStream outStream) throws IOExc
         longCoder.decode(inStream),
         longCoder.decode(inStream),
         KafkaTimestampType.forOrdinal(intCoder.decode(inStream)),
+        getHeaders(headerCoder.decode(inStream)),
         kvCoder.decode(inStream));
   }
 
+  private Headers getHeaders(Iterable<KV<String, byte[]>> records) {
```
Comment (rangadi) [inline sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java]: minor: call this `toHeaders()`? same for `getIterable()`

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: Thanks for the update. I missed later part of your comment above.

> and I package this class and use it as a dependency in another application which simply instantiates this class. Even though the downstream application did not call getHeaders, it will still throw a runtime exception.

Is that true? Can you try it with a small simple java class? I tested with a small test app and it worked ok . 
Run it with different versions of kafka, and with '-Dis.present=True|False':

````
package org.example;

import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.common.header.Headers;

public class TestRuntimeLoading {

  public static class A {

    Headers kafkaHeaders = null;

    Headers getHeaders(boolean isPresent) {
      if (isPresent && kafkaHeaders == null) {
        return new ConsumerRecord<>("test", 0, 0L, "key", "value").headers();
      } else {
        throw new RuntimeException("no headers");
      }
    }

  }

  public static void main(String[] args) {

    boolean isPresent = Boolean.valueOf(System.getProperty("is.present", "True"));
    Object headers = new A().getHeaders(isPresent);
    System.out.println("Headers : " + headers.toString());
  }
}
````

[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: Thank you for sharing this. Yes, this works as expected, but the issue comes when we initialize Headers in the if branch like so (similar to my example):

```java
if (isPresent && kafkaHeaders == null) {
        Headers headers = new RecordHeaders();
        headers.add("headerKey", "headerVal".getBytes());
        return new ConsumerRecord<>("test", 0, 0L, "key", "value").headers();
}
```
Even with is.present set to False, this throws a runtime exception.

[the remark this answers is not in the document]
Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecord.java]: hmm.. may be that is one of the reasons  `ConsumerRecord.headers()` returns mutable headers. Could we just use that?

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java [hunk 15]
```diff
@@ -212,6 +212,7 @@ public boolean advance() {
             rawRecord.offset(),
             consumerSpEL.getRecordTimestamp(rawRecord),
             consumerSpEL.getRecordTimestampType(rawRecord),
+            consumerSpEL.getHeaders(rawRecord),
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java]: Done

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java [hunk 16]
```diff
@@ -66,9 +76,34 @@ public void encode(KafkaRecord<K, V> value, OutputStream outStream) throws IOExc
...
         kvCoder.decode(inStream));
   }
 
+  private Object toHeaders(Iterable<KV<String, byte[]>> records) {
+    if (!records.iterator().hasNext()){
+      return null;
+    }
+
+    // ConsumerRecord is used to simply create a list of headers
+    ConsumerRecord<String, String> consumerRecord = new ConsumerRecord<>(
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java]: ```Headers headers = ... ```
raises a ```ClassNotFoundException``` when serializing ```KafkaRecordCoder```.

Updated to use empty strings instead of "key", "value"

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java [hunk 17]
```diff
@@ -66,9 +76,34 @@ public void encode(KafkaRecord<K, V> value, OutputStream outStream) throws IOExc
         longCoder.decode(inStream),
         longCoder.decode(inStream),
         KafkaTimestampType.forOrdinal(intCoder.decode(inStream)),
+        (Headers) toHeaders(headerCoder.decode(inStream)),
         kvCoder.decode(inStream));
   }
 
+  private Object toHeaders(Iterable<KV<String, byte[]>> records) {
+    if (!records.iterator().hasNext()){
+      return null;
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java]: Done

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java [hunk 18]
```diff
@@ -139,4 +156,11 @@ public long offsetForTime(Consumer<?, ?> consumer, TopicPartition topicPartition
       return offsetAndTimestamp.offset();
     }
   }
+
+  public Headers getHeaders(ConsumerRecord<byte[], byte[]> rawRecord) {
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java]: This is used by ```KafkaUnboundedReader```, would you like to move this logic to that class?

[the remark this answers is not in the document]
Comment (rangadi) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java]: Yes, that's that what I was thinking. 'hasHeaders' already used there.

[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ConsumerSpEL.java]: Done

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java [hunk 19]
```diff
@@ -66,9 +76,36 @@ public void encode(KafkaRecord<K, V> value, OutputStream outStream) throws IOExc
...
+    } else if (!records.iterator().hasNext()) {
+      return consumerRecord.headers();
+    }
+
+    records.forEach(kv -> consumerRecord.headers().add(kv.getKey(), kv.getValue()));
+    return consumerRecord.headers();
+  }
+
+  private Iterable<KV<String, byte[]>> toIterable(KafkaRecord record) {
+    if (!ConsumerSpEL.hasHeaders || record.getHeaders() == null){
```
[the remark this answers is not in the document]
Comment (gkumar7) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaRecordCoder.java]: ```record.getHeaders()``` could have been null when```toHeaders()``` returned null even if headers were supported (in the previous change I updated this to return an empty iterable of headers).

Agreed that it is not needed anymore.

**Comment by rangadi** [comment]
@gkumar7, did you push all your changes?

**Comment by gkumar7** [comment]
Yup
