### PR TITLE
remove sync stub list from GrpcWindmillServer

### PR DESCRIPTION
**Pull request by m-trieu**
remove sync stub for non appliance jobs.  this is no longer supported

r: @scwhittle 
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java [hunk 1]
```diff
@@ -360,69 +343,34 @@ private <ResponseT> ResponseT callWithBackoff(Supplier<ResponseT> function) {
...
-              syncApplianceStub
-                  .withDeadlineAfter(unaryDeadlineSeconds, TimeUnit.SECONDS)
-                  .getWork(request));
+    if (syncApplianceStub != null) {
+      return callWithBackoff(() -> syncApplianceStub.getWork(request));
     }
+
+    throw new RpcException(
+        new UnsupportedOperationException(
+            "Unary GetWork calls are not supported with Windmill service."));
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:352]: Streaming Engine is what dataflow docs refer to it as, can you update here and below? I see some usage of this text predates your change but let's make it clearer

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java [hunk 2]
```diff
@@ -242,17 +239,17 @@ private synchronized void initializeLocalHost(int port) {
     Channel channel = localhostChannel(port);
     if (options.isEnableStreamingEngine()) {
       this.stubList.add(CloudWindmillServiceV1Alpha1Grpc.newStub(channel));
-      this.syncStubList.add(CloudWindmillServiceV1Alpha1Grpc.newBlockingStub(channel));
     } else {
-      this.syncApplianceStub = WindmillApplianceGrpc.newBlockingStub(channel);
+      this.syncApplianceStub =
+          WindmillApplianceGrpc.newBlockingStub(channel)
+              .withDeadlineAfter(unaryDeadlineSeconds, TimeUnit.SECONDS);
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:245]: can unaryDeadlineSeconds be removed if the stub remembers it now?

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java [hunk 3]
```diff
@@ -480,30 +428,26 @@ public CommitWorkStream commitWorkStream() {
...
   public ReportStatsResponse reportStats(ReportStatsRequest request) {
-    if (syncApplianceStub == null) {
-      throw new RpcException(
-          new UnsupportedOperationException("ReportStats not supported with windmill service."));
-    } else {
+    if (syncApplianceStub != null) {
       return callWithBackoff(
           () ->
               syncApplianceStub
                   .withDeadlineAfter(unaryDeadlineSeconds, TimeUnit.SECONDS)
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:445]: remove deadline?

**Review by scwhittle — CHANGES_REQUESTED** [review]

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java (hunk 1 above)
Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:352]: done.

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java (hunk 2 above)
Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:245]: done.

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java (hunk 3 above)
Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:445]: done.

Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:445]: done.

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java (hunk 2 above)
Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:245]: done.

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java (hunk 1 above)
Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:352]: done.

**Comment by m-trieu** [comment]
retest this please

**Comment by m-trieu** [comment]
@scwhittle do you have any more comments for this pull request? Thank you!

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java [hunk 4]
```diff
@@ -238,34 +237,29 @@ public synchronized boolean isReady() {
...
     this.maxBackoff = Duration.millis(500);
-    this.unaryDeadlineSeconds = 10; // For local testing use short deadlines.
     Channel channel = localhostChannel(port);
     if (options.isEnableStreamingEngine()) {
       this.stubList.add(CloudWindmillServiceV1Alpha1Grpc.newStub(channel));
-      this.syncStubList.add(CloudWindmillServiceV1Alpha1Grpc.newBlockingStub(channel));
     } else {
-      this.syncApplianceStub = WindmillApplianceGrpc.newBlockingStub(channel);
+      this.syncApplianceStub =
+          WindmillApplianceGrpc.newBlockingStub(channel).withDeadlineAfter(10, TimeUnit.SECONDS);
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:245]: I remembered that I think this doesn't work as expected. The deadline is translated to an absolute timestamp here and thus all calls made with this stub will timeout after 10 seconds from when this is called (instead of a timeout on each call).

Could look into adding a test about that or at least add a comment for next time on why it is done for each call.

See https://github.com/grpc/grpc-java/issues/1495

Comment (scwhittle) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:245]: There may be a way to bind a call interceptor to set the deadline each time and thus set it up once here still.

Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java:245]: grpc/grpc-java/issues/4305 also found this which says that the stubs are meant to be forked and not cached. i will update

Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServer.java]: done. added an interceptor and documentation thanks for pointing this out

File: runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServerTest.java [hunk 5]
```diff
@@ -136,6 +146,65 @@ private <Stream extends StreamObserver> void maybeInjectError(Stream stream) {
...
+              MethodDescriptor<ReqT, RespT> methodDescriptor,
+              CallOptions callOptions,
+              Channel channel) {
+            if (deadline != null) {
+              // We want to assert that a new deadline is being created on every call since
+              // deadlines are absolute.
+              assertNotEquals(deadline, callOptions.getDeadline());
+            }
+
+            deadline = callOptions.getDeadline();
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServerTest.java:185]: nit: verify callOptions.getDeadline is non-null

**Review by scwhittle — APPROVED** [review]
LGTM with one nit. Thanks!

File: runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServerTest.java (hunk 5 above)
Comment (m-trieu) [reply runners/google-cloud-dataflow-java/worker/src/test/java/org/apache/beam/runners/dataflow/worker/windmill/grpcclient/GrpcWindmillServerTest.java:187]: done thanks Sam!

**Comment by m-trieu** [comment]
@jrmccluskey this is ready to merge got LGTM from @scwhittle 

Thanks!

**Comment by jrmccluskey** [comment]
Run Java PreCommit

**Comment by m-trieu** [comment]
@jrmccluskey The java precommit is an unrelated flake

same 2 tests failing in https://github.com/apache/beam/pull/28206

```
/runner/_work/beam/beam/sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/queries/Query5.java:68: error: cannot find symbol
```

**Comment by jrmccluskey** [comment]
Yeah I was trying to get a clean run, but run time + flakes were not cooperating. Merging!
